#
# Makefile for Imai Kobayashi Lab. command
#

TARGET	= SPTK.h

PREFIX	= /usr/local/SPTK
INCLUDE	= $(PREFIX)/include

RM	= rm -rf


all:

install:
	cp $(TARGET) $(INCLUDE)

clean:
	$(RM) \#* *~

veryclean: clean
	$(RM) $(INCLUDE)/$(TARGET)

